/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LabTestsRouteImport } from './routes/lab-tests'
import { Route as MedGamerRouteImport } from './routes/med-gamer'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as StoreRouteImport } from './routes/store'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as BookingNursingRouteImport } from './routes/booking.nursing'
import { Route as DoctorsSpecialtyRouteImport } from './routes/doctors.$specialty'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LabTestsRoute = LabTestsRouteImport.update({
  id: '/lab-tests',
  path: '/lab-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MedGamerRoute = MedGamerRouteImport.update({
  id: '/med-gamer',
  path: '/med-gamer',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingNursingRoute = BookingNursingRouteImport.update({
  id: '/booking/nursing',
  path: '/booking/nursing',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSpecialtyRoute = DoctorsSpecialtyRouteImport.update({
  id: '/doctors/$specialty',
  path: '/doctors/$specialty',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/inbox': typeof InboxRoute
  '/lab-tests': typeof LabTestsRoute
  '/med-gamer': typeof MedGamerRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/quiz': typeof QuizRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/worker': typeof WorkerRoute
  '/booking/nursing': typeof BookingNursingRoute
  '/doctors/$specialty': typeof DoctorsSpecialtyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/inbox': typeof InboxRoute
  '/lab-tests': typeof LabTestsRoute
  '/med-gamer': typeof MedGamerRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/quiz': typeof QuizRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/worker': typeof WorkerRoute
  '/booking/nursing': typeof BookingNursingRoute
  '/doctors/$specialty': typeof DoctorsSpecialtyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/career': typeof CareerRoute
  '/categories': typeof CategoriesRoute
  '/inbox': typeof InboxRoute
  '/lab-tests': typeof LabTestsRoute
  '/med-gamer': typeof MedGamerRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/quiz': typeof QuizRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/worker': typeof WorkerRoute
  '/booking/nursing': typeof BookingNursingRoute
  '/doctors/$specialty': typeof DoctorsSpecialtyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/career'
    | '/categories'
    | '/inbox'
    | '/lab-tests'
    | '/med-gamer'
    | '/more'
    | '/orders'
    | '/quiz'
    | '/store'
    | '/wallet'
    | '/worker'
    | '/booking/nursing'
    | '/doctors/$specialty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/career'
    | '/categories'
    | '/inbox'
    | '/lab-tests'
    | '/med-gamer'
    | '/more'
    | '/orders'
    | '/quiz'
    | '/store'
    | '/wallet'
    | '/worker'
    | '/booking/nursing'
    | '/doctors/$specialty'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/career'
    | '/categories'
    | '/inbox'
    | '/lab-tests'
    | '/med-gamer'
    | '/more'
    | '/orders'
    | '/quiz'
    | '/store'
    | '/wallet'
    | '/worker'
    | '/booking/nursing'
    | '/doctors/$specialty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CareerRoute: typeof CareerRoute
  CategoriesRoute: typeof CategoriesRoute
  InboxRoute: typeof InboxRoute
  LabTestsRoute: typeof LabTestsRoute
  MedGamerRoute: typeof MedGamerRoute
  MoreRoute: typeof MoreRoute
  OrdersRoute: typeof OrdersRoute
  QuizRoute: typeof QuizRoute
  StoreRoute: typeof StoreRoute
  WalletRoute: typeof WalletRoute
  WorkerRoute: typeof WorkerRoute
  BookingNursingRoute: typeof BookingNursingRoute
  DoctorsSpecialtyRoute: typeof DoctorsSpecialtyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-tests': {
      id: '/lab-tests'
      path: '/lab-tests'
      fullPath: '/lab-tests'
      preLoaderRoute: typeof LabTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/med-gamer': {
      id: '/med-gamer'
      path: '/med-gamer'
      fullPath: '/med-gamer'
      preLoaderRoute: typeof MedGamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/nursing': {
      id: '/booking/nursing'
      path: '/booking/nursing'
      fullPath: '/booking/nursing'
      preLoaderRoute: typeof BookingNursingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$specialty': {
      id: '/doctors/$specialty'
      path: '/doctors/$specialty'
      fullPath: '/doctors/$specialty'
      preLoaderRoute: typeof DoctorsSpecialtyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CareerRoute: CareerRoute,
  CategoriesRoute: CategoriesRoute,
  InboxRoute: InboxRoute,
  LabTestsRoute: LabTestsRoute,
  MedGamerRoute: MedGamerRoute,
  MoreRoute: MoreRoute,
  OrdersRoute: OrdersRoute,
  QuizRoute: QuizRoute,
  StoreRoute: StoreRoute,
  WalletRoute: WalletRoute,
  WorkerRoute: WorkerRoute,
  BookingNursingRoute: BookingNursingRoute,
  DoctorsSpecialtyRoute: DoctorsSpecialtyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
